###
GET http://localhost:3000/orders HTTP/1.1

###
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

{
    "amount": 1000.99
}

###
GET http://localhost:3000/orders/1 HTTP/1.1

###
PATCH http://localhost:3000/orders/1 HTTP/1.1
Content-Type: application/json

{
    "amount": 2000.99,
    "status": "approved"
}

###
DELETE  http://localhost:3000/orders/b2f15d3c-7903-43c2-8e50-a468ec5b29c6 HTTP/1.1

